### 유라시아 대륙 적설면적에 의한 황사 발생 분석

#### 프로젝트 선정 이유  

#### 프로젝트 구성  

#### 활용분야  

#### 프로젝트 발전가능성   

#### 후기

In [21]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
years = []
months = []
areas = []
with open("moncov.eurasia.txt", "r") as f:
    for line in f:
        year, month, area = map(int, line.rstrip().split())
        years.append(year)
        months.append(month)
        areas.append(area)

In [32]:
data = {
    'years' : years,
    'months' : months, 
    'areas' : areas
}
df = pd.DataFrame(data = data)
seasons = {
    12: 'Winter', 1: 'Winter', 2: 'Winter',
    3: 'Spring', 4: 'Spring', 5: 'Spring',
    6: 'Summer', 7: 'Summer', 8: 'Summer',
    9: 'Fall', 10: 'Fall', 11: 'Fall'
}

df['seasons'] = df['months'].map(seasons)

In [35]:
df[-12:]

     years  months     areas seasons
671   2023       7    217565  Summer
672   2023       8    175943  Summer
673   2023       9   1707980    Fall
674   2023      10  10578238    Fall
675   2023      11  21991107    Fall
676   2023      12  27533608  Winter
677   2024       1  28929663  Winter
678   2024       2  27914710  Winter
679   2024       3  23249284  Spring
680   2024       4  15864191  Spring
681   2024       5   9038478  Spring
682   2024       6   2052262  Summer

In [40]:
summer_2024 = df[(df['years'] == 2024) & (df['seasons'] == 'Summer')]

In [39]:
summer_2024

     years  months    areas seasons
682   2024       6  2052262  Summer

In [17]:
seoul = pd.read_csv('seoul.csv', encoding='euc-kr')
seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    55 non-null     int64
 1   1       55 non-null     float64
 2   2       55 non-null     float64
 3   3       55 non-null     float64
 4   4       55 non-null     float64
 5   5       55 non-null     float64
 6   6       55 non-null     float64
 7   7       55 non-null     float64
 8   8       55 non-null     float64
 9   9       55 non-null     float64
 10  10      55 non-null     float64
 11  11      55 non-null     float64
 12  12      55 non-null     float64
 13  total   55 non-null     float64
 14  rank    55 non-null     int64
dtypes: float64(13), int64(2)
memory usage: 6.6 KB

In [18]:
seoul

,year,1,2,3,4,5,6,7,8,9,10,11,12,total,rank
0,1970,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50
1,1971,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44
2,1972,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44
3,1973,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,42
4,1974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50
5,1975,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,37
6,1976,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,25
7,1977,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,25
8,1978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50
9,1979,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,36
10,1980,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,30
11,1981,0.0,0.0,2.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,15
12,1982,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,30
13,1983,0.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,30
14,1984,0.0,0.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,30
15,1985,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,42
16,1986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50
17,1987,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44
18,1988,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,22
19,1989,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50
20,1990,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,37
21,1991,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,11.0,12
22,1992,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,22
23,1993,0.0,0.0,0.0,10.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,6
24,1994,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50
25,1995,0.0,0.0,0.0,11.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,8
26,1996,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44
27,1997,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44
28,1998,0.0,0.0,3.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,8
29,1999,4.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,25
30,2000,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,15
31,2001,1.0,0.0,11.0,9.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,27.0,1
32,2002,2.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,16.0,3
33,2003,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,37
34,2004,0.0,1.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,25
35,2005,0.0,0.0,1.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,12.0,10
36,2006,0.0,0.0,3.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,12
37,2007,0.0,1.0,4.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,12.0,10
38,2008,0.0,1.0,3.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,11.0,12
39,2009,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,3.0,9.0,19
40,2010,1.0,0.0,4.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,15.0,4
41,2011,0.0,0.0,3.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,19
42,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,44
43,2013,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,37
44,2014,1.0,1.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,10.0,15
45,2015,1.0,4.0,8.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,4
46,2016,0.0,0.0,2.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,24
47,2017,1.0,0.0,0.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,10.0,15
48,2018,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,5.0,30
49,2019,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,3.0,37
50,2020,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,6.0,25
51,2021,2.0,0.0,5.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,6
52,2022,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,30
53,2023,4.0,0.0,6.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,2
54,2024,0.0,0.0,4.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,19